### ISSUE TITLE
Add a licence(?)

### ISSUE THREAD

**Issue by Clownacy** [cvghivebrain/HivePal2020#1]
Being open-source usually involves making the source code available under a licence, making it clear to users and fellow developers what they can and cannot do with it.

Two of the most common licences are MIT and GPL. MIT asks only that people who use your code to make another program give you credit, while GPL has the addition requirement that they too make their program open-source under the GPL.

GitHub has a little FAQ about licensing [here](https://choosealicense.com/). Licensing can be as simple as copying a text file into the Git repository. The GPL is a rather large and complex licence, while MIT is much smaller and easier to understand.

**Comment by cvghivebrain** [comment]
Done.
